openapi: 3.0.3
info:
  title: HR Recruiter - Generation API
  description: |
    API для генерации вакансий и вопросов с помощью AI.
    Отдельный модуль для всех операций генерации.
  version: 1.0.0
  contact:
    name: AI Team
    email: ai@hr-recruiter.com

servers:
  - url: /api/v1
    description: Основной API сервер

tags:
  - name: Generation
    description: Генерация вакансий и вопросов

paths:
  /generation/position/data:
    post:
      operationId: generatePositionData
      tags:
        - Generation
      summary: Генерировать основные данные вакансии
      description: |
        Генерирует структурированные данные вакансии на основе описания.
        Создает title, topics, status, tags, suggestedDescription.
        Используется для верхней кнопки генерации.
      security:
        - AdminAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PositionDataGenerationRequest'
      responses:
        '200':
          description: Данные успешно сгенерированы
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PositionDataGenerationResponse'
        '400':
          description: Неверный запрос
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Ошибка генерации
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /generation/position/questions:
    post:
      operationId: generatePositionQuestions
      tags:
        - Generation
      summary: Генерировать вопросы для вакансии
      description: |
        Генерирует список вопросов для собеседования на основе описания вакансии.
        Используется для нижней кнопки генерации.
      security:
        - AdminAuth: []
      parameters:
        - name: positionDescription
          in: query
          required: true
          schema:
            type: string
          description: Описание вакансии для генерации вопросов
        - name: questionsCount
          in: query
          required: false
          schema:
            type: integer
            default: 5
          description: Количество вопросов для генерации
      responses:
        '200':
          description: Вопросы успешно сгенерированы
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                description: Список сгенерированных вопросов
        '400':
          description: Неверный запрос
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Ошибка генерации
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /generation/question:
    post:
      operationId: generateQuestion
      tags:
        - Generation
      summary: Перегенерировать отдельный вопрос
      description: |
        Перегенерирует вопрос на основе нового описания вакансии.
        Принимает текущий вопрос и новое описание для перегенерации.
      security:
        - AdminAuth: []
      parameters:
        - name: currentQuestion
          in: query
          required: true
          schema:
            type: string
          description: Текущий вопрос для перегенерации
        - name: newDescription
          in: query
          required: true
          schema:
            type: string
          description: Новое описание вакансии
      responses:
        '200':
          description: Вопрос успешно перегенерирован
          content:
            application/json:
              schema:
                type: string
                description: Новый сгенерированный вопрос
        '400':
          description: Неверный запрос
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Ошибка генерации
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /generation/description:
    post:
      operationId: generateDescription
      tags:
        - Generation
      summary: Генерировать описание для overview
      description: |
        Генерирует краткое описание вакансии для предварительного просмотра.
        Не используется для создания или редактирования вакансии.
      security:
        - AdminAuth: []
      parameters:
        - name: positionDescription
          in: query
          required: true
          schema:
            type: string
          description: Описание вакансии для генерации overview
      responses:
        '200':
          description: Описание успешно сгенерировано
          content:
            application/json:
              schema:
                type: string
                description: Сгенерированное описание для overview
        '400':
          description: Неверный запрос
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Ошибка генерации
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  securitySchemes:
    AdminAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    PositionDataGenerationRequest:
      type: object
      properties:
        description:
          type: string
          description: Описание вакансии для генерации данных
          example: Нужен Java разработчик для разработки микросервисов
        existingData:
          type: object
          description: Существующие данные вакансии (опционально)
          properties:
            title:
              type: string
              description: Существующий заголовок
            topics:
              type: array
              items:
                type: string
              description: Существующие темы
            status:
              type: string
              description: Существующий статус
            tags:
              type: array
              items:
                type: string
              description: Существующие теги
            suggestedDescription:
              type: string
              description: Существующее описание
      required:
        - description

    PositionDataGenerationResponse:
      type: object
      properties:
        generatedData:
          type: object
          properties:
            title:
              type: string
              description: Сгенерированный заголовок вакансии
              example: Java Backend Developer
            topics:
              type: array
              items:
                type: string
              description: Сгенерированные темы для собеседования
              example:
                - Java Core
                - Spring Framework
                - Microservices
                - Database Design
            status:
              type: string
              enum:
                - DRAFT
                - PUBLISHED
                - CLOSED
                - ARCHIVED
              description: Предлагаемый статус позиции
              example: DRAFT
            level:
              type: string
              enum:
                - JUNIOR
                - MIDDLE
                - SENIOR
                - LEAD
              description: Предлагаемый уровень позиции
              example: MIDDLE
            tags:
              type: array
              items:
                type: string
              description: Сгенерированные теги
              example:
                - Java
                - Backend
                - Spring
                - Microservices
            suggestedDescription:
              type: string
              description: Улучшенное описание вакансии
        confidence:
          type: number
          format: float
          description: Уверенность в генерации (0-1)
          example: 0.85
        message:
          type: string
          description: Сообщение о результатах генерации
          example: Данные успешно сгенерированы на основе описания

    ErrorResponse:
      type: object
      properties:
        message:
          type: string
          description: Сообщение об ошибке
          example: Произошла ошибка при обработке запроса
        error:
          type: string
          description: Тип ошибки
          example: VALIDATION_ERROR
        timestamp:
          type: string
          format: date-time
          description: Время возникновения ошибки
          example: '2024-01-15T10:30:45Z'
        path:
          type: string
          description: Путь запроса
          example: /api/generation
      required:
        - message
        - error
        - timestamp 